## **Transforming, Grouping & Sorting Data**
### Data transformation.
To map our data, is to use a function that enables us to take one set of values and "map" them to another set of values. Why would one do this? In data science, we often have to create a new representation from the exisiting data, or we need to transform our data from the current format to a different format to do downstream analysis. In this notebook we will introduce two mapping methods; `map()` and `apply()`. We will work with the crime dataset to practice these methods.

&nbsp;
### Learning outcome:
- To learn how to transform our data (series or dataframe) using `map()` and `apply()` for mapping values
- Use `lambda` for column and row operations when we use mapping function.
- Introduce methods to aggregate data points using `groupby()` and working with Multiindex

### Class examples in lecture M02_pandas-2-grouping

In [ ]:
import pandas as pd
import numpy as np
from numpy import nan

In [2]:
df = pd.DataFrame({'Genre': ['Action', 'Comedy', 'Drama', 'Horror']})
genre_map = {'Action':'A', 'Comedy':'C', 'Drama':'D', 'Horror':'H'}

### map()
df['Genre code'] = df['Genre'].map(genre_map)
display(df)

### apply() on a series
df['Genre'].apply(lambda genre: genre_map[genre])


,Genre,Genre code
0,Action,A
1,Comedy,C
2,Drama,D
3,Horror,H


0    A
1    C
2    D
3    H
Name: Genre, dtype: str

In [ ]:
df2 = pd.DataFrame({"P":[9,9,9], "Q":[25,25,25]})
# df2 = df2.apply(np.sqrt)

**Class activity** L5 -  Pandas 2 - Grouping
*  What would be return if in column P for index 2 the value is nan?
*   What would be the output of `df.apply(np.sum, axis=1)`?

In [4]:
### What would be return if in column P for index 2 the value is nan when we run function `df.apply(np.sum)`?
df2 = pd.DataFrame({"P":[9, 9, nan], "Q":[25, 25, 25]})

# Pandas sum skips NaN by default: P totals 18 and Q totals 75.
df2.apply(np.sum)


P    18.0
Q    75.0
dtype: float64

In [5]:
### What would be the output of df.apply(np.sum, axis=1)?
# Your code

# Row totals are 34, 34, and 25; the missing P value is skipped.
df2.apply(np.sum, axis=1)


0    34.0
1    34.0
2    25.0
dtype: float64

###  **Crime Rates Dataset**
We will continue to use the crime rate dataset from M02_L04_intro-pandas

In [ ]:
# Importing libraries
import pandas as pd
pd.options.display.float_format = "{:,.2f}".format

In [7]:
### Let's review how to read a csv in a dataframe and change header column names
url='https://raw.githubusercontent.com/csbfx/advpy122-data/master/crime_rates.csv'
new_colnames=['state', 'year', 'pop', 'violent', 'murder', 'rape', 'robbery', 'assault', 'property', 'burglary', 'larceny','vehicle']

crime_rates = pd.read_csv(url, names=new_colnames, header=0)


In [8]:
## A reminder of what columns are in this dataset and the size of the dataframe *hint info

crime_rates.info()


<class 'pandas.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   state     2200 non-null   str    
 1   year      2200 non-null   int64  
 2   pop       2200 non-null   int64  
 3   violent   2200 non-null   float64
 4   murder    2200 non-null   float64
 5   rape      2200 non-null   float64
 6   robbery   2200 non-null   float64
 7   assault   2200 non-null   float64
 8   property  2200 non-null   float64
 9   burglary  2200 non-null   float64
 10  larceny   2200 non-null   float64
 11  vehicle   2200 non-null   float64
dtypes: float64(9), int64(2), str(1)
memory usage: 206.4 KB


In [9]:
## To show the statistic of our int columns, notice 'state' not included in the table *hint describe

crime_rates.describe()


,year,pop,violent,murder,rape,robbery,assault,property,burglary,larceny,vehicle
count,"2,200.00","2,200.00","2,200.00","2,200.00","2,200.00","2,200.00","2,200.00","2,200.00","2,200.00","2,200.00","2,200.00"
mean,"1,981.50","4,609,092.06",369.86,6.38,26.86,115.55,221.07,"3,736.73",965.01,"2,412.48",359.23
std,12.70,"5,009,459.77",243.08,3.76,15.83,98.88,151.98,"1,454.85",446.38,955.27,207.75
min,"1,960.00","226,167.00",9.50,0.20,0.80,1.90,3.60,573.10,182.60,293.30,48.30
25%,"1,970.75","1,182,750.00",173.30,3.20,14.58,38.07,100.97,"2,640.65",618.63,"1,700.40",195.90
50%,"1,981.50","3,187,500.00",320.90,5.70,25.40,93.85,190.75,"3,815.75",910.45,"2,495.15",324.45
75%,"1,992.25","5,440,050.25",522.65,9.10,36.73,160.40,308.18,"4,703.53","1,232.68","3,025.53",471.10
max,"2,003.00","35,484,453.00","1,244.30",20.30,102.20,684.00,785.70,"7,996.00","2,906.70","5,106.10","1,571.10"


##  Dropping columns with `drop()`
This data set as we previously observed is clean and does not have redundant data. For practice, we will assume that we do not need the column "year" or "pop".  Pandas DataFrame method `drop()` will return a new DataFrame by default but it will not overwrite the current DataFrame. If you want to overwrite the current DataFrame, you can set the argument `inplace=True`.  

&nbsp;
The drop() method can drop either rows or columns. The default is rows (`axis=0`). To drop columns, set the argument to `axis=1`.

In [10]:
# drop these columns 'year','pop'
crime_rates_dropped = crime_rates.drop(columns=['year', 'pop'])
crime_rates_dropped.head()


,state,violent,murder,rape,robbery,assault,property,burglary,larceny,vehicle
0,Alaska,104.30,10.20,20.80,28.30,45.10,"1,544.90",332.10,970.50,242.30
1,Alaska,88.90,11.50,13.20,12.40,51.70,"1,540.60",380.80,950.00,209.80
2,Alaska,91.50,4.50,18.70,13.80,54.50,"1,564.60",351.60,985.40,227.60
3,Alaska,109.70,6.50,14.90,22.20,66.10,"1,952.80",381.50,"1,213.70",357.70
4,Alaska,150.00,10.40,22.40,21.20,96.00,"2,016.00",443.60,"1,218.40",354.00


###  Mapping values with `map()`
The Series method [`map()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.map.html) maps values of Series according to an input function and returns a new Series.   

> `new_series = a_series.map(some_function)`

Map expect either a dictionary for direct lookups or a single-argument function (like a lambda function) that will be applied to each element of the Series.

**Scenario**: Suppose that we wanted to redefine states to broad region using a mapping function.

We will be using a `lambda` function in the example below. You can review Python lambda function [here](https://www.w3schools.com/python/python_lambda.asp).

In [11]:
### Use a dictionary to define the regions of the USA.
region_map = {
    'California': 'West',
    'Washington': 'West',
    'New York': 'Northeast',
    'Illinois': 'Midwest',
    'Colorado': 'Midwest',
    'Alabama': 'South',
    'Arkansas': 'South',
    'Arizona': 'South',
    'Texas': 'South',
    'Georgia': 'South',
    'Florida': 'South'
}

### Use map to define the regions based on the dictionary region_map
crime_rates['region'] = crime_rates['state'].map(region_map)

## What if you do not know what region a state is in and you want to add the value 'other' for all states without a defined region
## Try doing this in one line with lambda
crime_rates['region'] = crime_rates['state'].map(lambda state: region_map.get(state, 'other'))
display(crime_rates[['state', 'region']].drop_duplicates())


## Try filtering for particular columns or dropping duplicates
# Note neither of these commands overwrite the DataFrame
# crime_rates[['state','region']].head()
# crime_rates[['state','Region']].drop_duplicates().head()


,state,region
0,Alaska,other
44,Alabama,South
88,Arkansas,South
132,Arizona,South
176,California,West
220,Colorado,Midwest
264,Connecticut,other
308,Delaware,other
352,Florida,South
396,Georgia,South


The function you pass to `map()` should expect a single value from the Series (a point value, in the above example), and return a transformed version of that value. `map()` returns a new Series where all the values have been transformed by your function.

Create a new column called 'pop-scale', which stores the values we define as the scale of a population, depending on the size of the population. We know from using
> `crime_rates.describe()`

that the population ranges from 226,167.00 to 35,484,453.00. We define:
-  \> 20,000,001.00 is **3** (large population)
-  between 1,000,001.00 and 20,000,000.00 is **2** (midsize population)
-  below 1,000,000.00 is **1** (small population)

In [12]:
### Create function to do transformation for map()
## Since we are only looking at population(a single column), we do not need to use apply()

def pop_scale(x): # x is going to be a value from the Series
    if x > 20000001:
        return 3
    elif 1000001 < x <= 20000000:
        return 2
    else:
        return 1

## Use map to return a Series called 'scale' that contains the population scaled values

scale = crime_rates['pop'].map(pop_scale)

## Add the Series 'scale' to new column, 'pop_scale' in crime_rate DataFrame
crime_rates['pop_scale'] = scale
crime_rates[['state', 'pop', 'pop_scale']].head()


,state,pop,pop_scale
0,Alaska,226167,1
1,Alaska,234000,1
2,Alaska,246000,1
3,Alaska,248000,1
4,Alaska,250000,1


##  Applying transformations with `apply()`
The DataFrame method, [`apply()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html), should be used if we want to <u>transform the whole DataFrame</u> by calling a custom method on each row. We can use `apply()` to pass a function and apply it on every single value of the panda series.  

Below we will call `crime_rates.apply()` with `axis='columns'`. If we use `axis='index'`, then instead of passing a function to transform each row for the column(s), we would need to provide a function to transform each column for the row(s).

Recall:  
- **Single column:** similar to `.map()`.
- **Row-wise operations:** use `axis='columns'` or `axis=1`
- **Column-wise operations:** use `axis=0` (or 'index')

In [ ]:
## We are going to define 'crime_level' based on the rate of violent crimes
crime_rates['crime_level'] = crime_rates['violent'].apply(
    lambda x: 'High' if x > 1000
    else ('Med' if 999 > x > 500 else 'Low')
)

crime_rates[['violent', 'crime_level']].head()

,violent,crime_level
0,104.300003,Low
1,88.900002,Low
2,91.500000,Low
3,109.699997,Low
4,150.000000,Low


In [ ]:
## Combine multiple types of crime to get the total crime rate
crime_rates['total_crime'] = crime_rates.apply(
    lambda row: row['violent'] + row['murder'] + row['assault'],
    axis='columns',
)
crime_rates[['violent','murder', 'assault', 'total_crime']].head()

,violent,murder,assault,total_crime
0,104.30,10.20,45.10,159.60
1,88.90,11.50,51.70,152.10
2,91.50,4.50,54.50,150.50
3,109.70,6.50,66.10,182.30
4,150.00,10.40,96.00,256.40


When we are performing an operation between a lot of values, pandas looks at the expression and figures out that we must mean to do the mathematical expression on in the dataset.

Pandas will also understand what to do if we perform these operations between Series of equal length. For example, we combine the values of different crime type in the dataset. You can also combine strings, but you can not combine int and string values.

**Note:**
`map()` and `apply()` **return new, transformed Series and DataFrames, respectively**. They <i>**don't modify**</i> the original data they're called on.

# Groupwise analysis
Any time we see a question involving the words, ”how many ..." or "for each ...”, the answer is `value_counts`.

In [ ]:
### How many states have the high level of crime?
crime_rates['crime_level'].value_counts()

We can replicate what `value_counts()` does by implementing `groupby`.

In [ ]:
### Count numbers of instance of each 'crime_level' through groups
crime_rates.groupby('crime_level').state.count()

[`groupby()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.groupby.html) created different category of crime level based on the number of violet crime rates to a given state. For each of these groups, we grabbed the `crime_level()` column and counted how many times it appeared. value_counts() is just a shortcut to this `groupby()` operation.

We can use any of the summary functions with this data. For example, to get the lowest violent crime rate for each year, we can use `min()` on the 'violent' column.

In [ ]:
### What is the lowest value of violent crime for each year?
crime_rates.groupby('year').violent.min().head()

In [ ]:
## To get the state that is associated with the groupby, we can reference the index
min_violent_by_year_index = crime_rates.groupby('year')['violent'].idxmin()

## Use .loc to pull out the rows that contain the index of interest
state_with_min_violent = crime_rates.loc[min_violent_by_year_index, ['year', 'state', 'violent']]
state_with_min_violent.head()

You can think of each group we generate as being a slice of our DataFrame containing only data with values that match. This DataFrame is accessible to us directly using the `apply()` method, and we can then manipulate the data in any way we see fit.

##  Aggregation with `groupby()`
Another `groupby()` method worth mentioning is `agg()`, which lets you run a bunch of different functions on your DataFrame simultaneously. For example, we can generate a simple statistical summary of the dataset through `groupby()` 'year', and compute the mean values for the different crime types across the states.

In [ ]:
### This method calculates the mean value and is shorthand for agg()
group_mean = crime_rates.groupby(['year'])[
    ['violent', 'murder', 'assault']].mean()
group_mean.head()

In [ ]:
### agg() method
group_mean_agg = crime_rates.groupby('year').agg({
                                'violent': 'mean',
                                'murder': 'mean',
                                'assault': 'mean'})
group_mean_agg.head()

## Multi-Index

In all of the examples we've seen thus far we've been working with DataFrame or Series objects with a single-label index. `groupby()` is slightly different in the fact that, depending on the operation we run, it will sometimes result in what is called a multi-index.

A multi-index differs from a regular index in that it has multiple levels. Multi-indices have several methods for dealing with their tiered structure which are absent for single-level indices. They also require two levels of labels to retrieve a value. Dealing with multi-index output is a common "gotcha" for users new to pandas.

The use cases for a multi-index are detailed alongside instructions on using them in the [MultiIndex / Advanced Selection](https://pandas.pydata.org/pandas-docs/stable/user_guide/advanced.html) section of the pandas documentation.

However, in general the multi-index method you will use most often is the one for converting back to a regular index, the `reset_index()` method:

In [ ]:
### Convert multi-index to regular flat index
group_mean_agg_flat = group_mean_agg.reset_index()

# Sorting
Looking again at `state_with_min_violent` we can see that grouping returns data in index order, not in value order. That is to say, when outputting the result of a `groupby`, the order of the rows is dependent on the values in the index, not in the data.

To get data in the order want it in we can sort it ourselves. The `sort_values()` method is handy for this. [`sort_values()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sort_values.html) defaults to an ascending sort, where the lowest values go first. However, most of the time we want a descending sort, where the higher numbers go first.

##  Sorting with `sort_values()`

In [ ]:
sorted_df = state_with_min_violent.sort_values(
    by=['year','state', 'violent'],
    ascending=[False, False, True]
)
sorted_df.head()

##  Class Exercise

### Class Exercise CL5.1
Identify the top three states per year by "property" crime rates.

_Hint:_
*   `DataFrame.nlargest(n, columns, keep='first')` is used to retrieve the first n rows with the largest values from a DataFrame

In [23]:
# Your code

top_three = crime_rates.groupby('year')['property'].nlargest(3)
top_three_indices = top_three.index.get_level_values(1)
crime_rates.loc[top_three_indices, ['year', 'state', 'property']].sort_values(
    ['year', 'property'], ascending=[True, False])


,year,state,property
1408,1960,Nevada,"3,294.70"
176,1960,California,"3,235.40"
132,1960,Arizona,"2,806.00"
1409,1961,Nevada,"3,436.80"
177,1961,California,"3,177.50"
...,...,...,...
482,2002,Hawaii,"5,801.40"
2066,2002,Washington,"4,762.90"
175,2003,Arizona,"5,632.40"
483,2003,Hawaii,"5,237.50"


### Class Exercise CL5.2
*Normalize Violent Crime Rate*

Compute a new column, violent_rate_per_100k, that represents violent incidents per 100,000 people:

violent_rate_per_100k = violent / pop * 100000

Use `apply()` either column-wise or row-wise to perform the calculation.

In [24]:
# Your code

# Follow the requested formula. The source's violent column is already a rate,
# so this exercise's result should not be interpreted as a new incident rate.
crime_rates['violent_rate_per_100k'] = crime_rates.apply(
    lambda row: row['violent'] / row['pop'] * 100000, axis=1)
crime_rates[['state', 'year', 'violent', 'pop', 'violent_rate_per_100k']].head()


,state,year,violent,pop,violent_rate_per_100k
0,Alaska,1960,104.30,226167,46.12
1,Alaska,1961,88.90,234000,37.99
2,Alaska,1962,91.50,246000,37.20
3,Alaska,1963,109.70,248000,44.23
4,Alaska,1964,150.00,250000,60.00


### Class Exercise CL5.3
_Understanding total crime rates_  

Group by `year` and `state`, sum the rate of `violent`, `property`, `burgalry`, `larceny`, `vehicle` crimes into `crime_total`. Sort the DataFrame by `year` and `crime_total`.

In [25]:
# Your code

crime_columns = ['violent', 'property', 'burglary', 'larceny', 'vehicle']
crime_by_state_year = crime_rates.groupby(['year', 'state'])[crime_columns].sum()
crime_by_state_year['crime_total'] = crime_by_state_year.sum(axis=1)
crime_by_state_year = crime_by_state_year.reset_index().sort_values(['year', 'crime_total'])
# Property crime includes its component offenses, so this requested sum double-counts them.
crime_by_state_year


,year,state,violent,property,burglary,larceny,vehicle,crime_total
23,1960,Mississippi,102.70,602.00,204.70,349.10,48.30,"1,306.80"
28,1960,New Hampshire,13.30,676.40,182.60,436.00,57.80,"1,366.10"
47,1960,West Virginia,64.50,656.20,234.20,352.50,69.40,"1,376.80"
44,1960,Vermont,9.50,815.90,242.10,486.80,86.90,"1,641.20"
33,1960,North Dakota,14.20,876.80,198.00,610.80,68.00,"1,767.80"
...,...,...,...,...,...,...,...,...
2189,2003,South Carolina,793.50,"4,477.10","1,050.90","3,046.10",380.10,"9,747.70"
2196,2003,Washington,347.00,"4,754.90",950.30,"3,142.10",662.50,"9,856.80"
2186,2003,Oregon,295.50,"4,782.30",804.20,"3,444.60",533.50,"9,860.10"
2160,2003,Hawaii,270.40,"5,237.50",907.20,"3,562.90",767.40,"10,745.40"


### Class Exercise CL5.4
*Crime Change by State year over year*  
Use `groupby()` and `shift()` to compute the percentage change in 'violent' crime compared to the previous year for each state. You will want to group by state and sort_values() to display your data chronologically.  
_Hint_:

* `shift()` removes the first element from the array and returns that removed element.

In [26]:
# Your code

crime_change = crime_rates.sort_values(['state', 'year']).copy()
previous_violent = crime_change.groupby('state')['violent'].shift(1)
crime_change['violent_pct_change'] = (
    (crime_change['violent'] - previous_violent) / previous_violent.replace(0, np.nan) * 100
)
# The first observation for each state has no previous year, so its change is NaN.
crime_change[['state', 'year', 'violent', 'violent_pct_change']]


,state,year,violent,violent_pct_change
44,Alabama,1960,186.60,NaN
45,Alabama,1961,168.50,-9.70
46,Alabama,1962,157.30,-6.65
47,Alabama,1963,182.70,16.15
48,Alabama,1964,213.10,16.64
...,...,...,...,...
2195,Wyoming,1999,232.50,-6.10
2196,Wyoming,2000,266.50,14.62
2197,Wyoming,2001,257.30,-3.45
2198,Wyoming,2002,273.40,6.26
